✨ Adding custom metrics
boring-registry/boring-registry pull request #177
Opened 2024-03-28 14:08 UTC by XREvo

# What is the topic of this PR

It add custom new metrics to the `/metrics` endpoint.

## Boring's metrics

It adds 3 metrics dédicated to boring : 
|Name|Type|Description|Labels|
|---|---|---|---|
|boring_registry_providers_list_versions|counter|Number of boring's providers versions listing.|namespace, name|
|boring_registry_providers_download_version|counter|Number of boring's providers download.|namespace, name, version, os, arch|
|boring_registry_modules_list_versions|counter|Number of boring's modules versions listing.|namespace, name, provider|
|boring_registry_modules_download_version|counter|Number of boring's modules download.|namespace, name, provider, version|
|boring_registry_mirrors_list_provider_versions|counter|Number providers versions listing on the mirror.|hostname, namespace, name|
|boring_registry_mirrors_list_provider_installations|counter|Number providers retreive and archive on the mirror.|hostname, namespace, name, version|
|boring_registry_mirrors_download_version|counter|Number of boring's modules download.|hostname, namespace, name, version, os, arch|

## "Global" metrics

It add 4 global metrics, dedicated to HTTP traffic: 
|Name|Type|Description|Labels|
|---|---|---|---|
|http_request_total|counter|Tracks the number of HTTP requests.|method, code|
|http_request_duration_seconds|histogram|Tracks the latencies for HTTP requests.|method, code|
|http_request_size_bytes|summary|Tracks the size of HTTP requests.|method, code|
|http_response_size_bytes|summary|Tracks the size of HTTP responses.|method, code|

## Final content rendered

The added content looks like this :
```
# HELP boring_registry_providers_download_version Number of boring's providers download.
# TYPE boring_registry_providers_download_version counter
boring_registry_providers_download_version{arch="amd64",name="the-ring",namespace="lord-of",os="linux",version="0.2.6"} 3
# HELP boring_registry_providers_list_versions Number of boring's providers versions listing.
# TYPE boring_registry_providers_list_versions counter
boring_registry_providers_list_versions{name="the-ring",namespace="lord-of"} 3
# HELP http_request_duration_seconds Tracks the latencies for HTTP requests.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{code="200",method="get",le="0.1"} 2
http_request_duration_seconds_bucket{code="200",method="get",le="0.15000000000000002"} 2
http_request_duration_seconds_bucket{code="200",method="get",le="0.22500000000000003"} 2
http_request_duration_seconds_bucket{code="200",method="get",le="0.3375"} 2
http_request_duration_seconds_bucket{code="200",method="get",le="0.5062500000000001"} 2
http_request_duration_seconds_bucket{code="200",method="get",le="+Inf"} 3
http_request_duration_seconds_sum{code="200",method="get"} 29.646969346000002
http_request_duration_seconds_count{code="200",method="get"} 3
http_request_duration_seconds_bucket{code="500",method="get",le="0.1"} 0
http_request_duration_seconds_bucket{code="500",method="get",le="0.15000000000000002"} 0
http_request_duration_seconds_bucket{code="500",method="get",le="0.22500000000000003"} 0
http_request_duration_seconds_bucket{code="500",method="get",le="0.3375"} 0
http_request_duration_seconds_bucket{code="500",method="get",le="0.5062500000000001"} 0
http_request_duration_seconds_bucket{code="500",method="get",le="+Inf"} 1
http_request_duration_seconds_sum{code="500",method="get"} 30.27717207
http_request_duration_seconds_count{code="500",method="get"} 1
# HELP http_request_size_bytes Tracks the size of HTTP requests.
# TYPE http_request_size_bytes summary
http_request_size_bytes_sum{code="200",method="get"} 2061
http_request_size_bytes_count{code="200",method="get"} 3
http_request_size_bytes_sum{code="500",method="get"} 699
http_request_size_bytes_count{code="500",method="get"} 1
# HELP http_request_total Tracks the number of HTTP requests.
# TYPE http_request_total counter
http_request_total{code="200",method="get"} 3
http_request_total{code="500",method="get"} 1
# HELP http_response_size_bytes Tracks the size of HTTP responses.
# TYPE http_response_size_bytes summary
http_response_size_bytes_sum{code="200",method="get"} 7035
http_response_size_bytes_count{code="200",method="get"} 3
http_response_size_bytes_sum{code="500",method="get"} 3959
http_response_size_bytes_count{code="500",method="get"} 1
```

2024-04-08 20:50 UTC, oliviermichaelis requested changes
Hi @XREvo ! First of all, thank you for the contribution :)
Took me a while to find the time to review it, sorry for that.

Thank you for the great overview of the metrics and also the `/metrics` response in the issue description. It definitely helps to get an overview quickly!
In general, everything looks good from my side, I don't see any major problems with the PR.
However, there are some small adjustments that I'm asking for. I don't think that they should take much time to implement. Let me know if you have any questions or if I can clarify something.

Also, the next time you want to contribute, consider opening a GitHub issue first. This allows us to discuss the changes and how to implement it, without you possibly wasting time on the implementation. I think this probably applies to most source project :)

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/observability/metrics.go
> +		buckets = prometheus.ExponentialBuckets(0.1, 1.5, 5)
I think we definitely need more buckets, as we can experience a wide variance of durations.
What about `buckets = prometheus.ExponentialBuckets(0.05, 1.6, 10)`?

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/observability/metrics.go
> +	response_subsystem := "response"
Let's not use snake case, but the de-facto camelCase standard for Go please :)

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/observability/metrics.go
> +	Providers *ProvidersMetrics
Can we use singular for the struct fields? (e.g. `Mirrors` -> `Mirror`)

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/observability/metrics.go
> +					Name:      "list_provider_versions",
Most counters are missing the count suffix (`_total`) in the name. Can you add it please?

Also, this document might be relevant to you: https://prometheus.io/docs/practices/naming/

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/observability/metrics.go
> +					Help:      "Number providers versions listing on the mirror.",
Can you please omit all the traling dots (`.`) from the help strings?

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/observability/metrics.go
> +					Help:      "Number of boring's providers versions listing.",
Personally, I feel like most of the metric help strings are a bit difficult to understand. Can you please rewrite them?

For example, we can rewrite `"Number of boring's providers versions listing."` to `"The total number of provider version requests"`. Merci!

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/mirror/endpoint.go
> +	"github.com/prometheus/client_golang/prometheus"
nit: can you please group the imports according to the existing "logic"? I think this applies to some other files as well. Thanks!

2024-04-08 20:50 UTC, oliviermichaelis commented on pkg/mirror/endpoint.go
> +			"name":      req.Name,
Can we create constants in the `observability` module for the names of the labels?
For example something like this:
```go
const (
	HostnameLabel  = "hostname"
	NamespaceLabel = "namespace"
	...
)
```
and then we can use them like this:
```go
		metrics.ListProviderVersions.With(prometheus.Labels{
			o11y.HostnameLabel:  req.Hostname,
			o11y.NamespaceLabel: req.Namespace,
			o11y.NameLabel:     req.Name,
		}).Inc()
```
This will help us to ensure that we don't accidentally have diverging labels in the future :)

2024-04-09 08:01 UTC, XREvo commented
Thanks for the review!  
I'll fix all your comments soon (probably tomorrow)

And you are right, i should have opened an issue like on any other open source project (my apologies 🙏).

2024-04-10 19:50 UTC, XREvo commented on pkg/observability/metrics.go
> +		buckets = prometheus.ExponentialBuckets(0.1, 1.5, 5)
That a good point. The S3 we use internally use quite efficient, but it might not be the case for every one.

I'll change it.

2024-04-10 19:51 UTC, XREvo commented on pkg/observability/metrics.go
> +					Help:      "Number of boring's providers versions listing.",
My bad! It's a french reflex 😅

2024-04-10 19:51 UTC, XREvo commented on pkg/observability/metrics.go
> +					Help:      "Number providers versions listing on the mirror.",
My bad! It's a french reflex 😅

2024-04-15 19:54 UTC, oliviermichaelis commented
Hi @XREvo, have you made any progress? Is there anything I could help you with? :)

2024-04-16 07:22 UTC, XREvo commented
Yes i've started to fix my code, but i struggled to find time to finish it (i'm doing it on my spare time, that's why i'm strugling to find time).  
But i have done nearly 80% of the fixes so i think that at the end of the week it will be finished

2024-04-16 15:02 UTC, oliviermichaelis approved these changes
LGTM :tada: Thanks for your contribution!:)

2024-04-19 20:41 UTC, merged