:sparkles: Introduce proxy download
boring-registry/boring-registry pull request #181
Opened 2024-05-31 21:45 UTC by XREvo

This PR relates to Issue https://github.com/boring-registry/boring-registry/issues/180

This is still a work in progress (even it's fully functionnal).

Merging shoudl only be considered when an agreement will be acquired on the Issue https://github.com/boring-registry/boring-registry/issues/180

2024-06-25 21:16 UTC, oliviermichaelis reviewed
Thanks for your work @XREvo!

I reviewed the code and left some final comments :)

I haven't tested the changes properly yet. Once I find the time, I'll make sure to test it with the remaining storage providers

2024-06-25 21:16 UTC, oliviermichaelis commented on pkg/core/proxifier.go
> +		return "", fmt.Errorf("downloadUrl cannot be parsed: %s", downloadUrl)
Can you add the `err` from the `url.ParseRequestURI()` call to the error message?

2024-06-25 21:16 UTC, oliviermichaelis commented on pkg/core/proxifier.go
> +	excapedUrl := url.QueryEscape(pathUrl)
typo: should be `excapedUrl()`

2024-06-25 21:16 UTC, oliviermichaelis commented on pkg/core/proxifier.go
> +	// Find the protocol (http ou https)
typo: `http or https`

2024-06-25 21:16 UTC, oliviermichaelis commented on pkg/module/transport.go
> +					httptransport.ServerBefore(core.ExtractRootUrl()),
Why do we call this here? Don't we only need to add it for the download of the module in line 56?

2024-06-25 21:16 UTC, oliviermichaelis commented on pkg/proxy/endpoint.go
> +		metrics.Download.With(prometheus.Labels{}).Inc()
The `With(prometheus.Labels{})` is dead code, can you please remove it?

2024-06-25 21:16 UTC, oliviermichaelis commented on pkg/proxy/errors.go
> +	ErrCantDownloadFile  = errors.New("remote file failed to download")
nit: I would suggest `ErrCannotDownloadFile` :)

2024-06-25 21:16 UTC, oliviermichaelis commented on pkg/proxy/endpoint.go
> +		return "", fmt.Errorf("downloadUrl cannot be parsed: %s", downloadUrl)
Can you please add the `err` in the error message?

2024-06-25 21:16 UTC, oliviermichaelis commented on cmd/root.go
> +	rootCmd.PersistentFlags().BoolVar(&flagProxy, "proxy", false, "Enable proxying download request to remote storage")
The flag shouldn't be part of the `rootCmd`, but part of the `serverCmd`. The `rootCmd` has all configuration options that apply to all commands, but the `flagProxy` is only necessary for the `server` command :)

Also, can we rename the flag to make it more specific? We might get another proxy feature in the future, I think we should find the best possible name right now to prevent breaking it in the future. What do you think about `download-proxy`?

2024-06-26 12:01 UTC, XREvo commented on cmd/root.go
> +	rootCmd.PersistentFlags().BoolVar(&flagProxy, "proxy", false, "Enable proxying download request to remote storage")
You are right!

I didn't get it in mind when adding it here. I'll move it to `serverCmd` and rename it as suggested

2024-06-26 12:10 UTC, XREvo commented on pkg/core/proxifier.go
> +	// Find the protocol (http ou https)
French reflex...sorry

2024-06-26 12:13 UTC, XREvo commented on pkg/module/transport.go
> +					httptransport.ServerBefore(core.ExtractRootUrl()),
Since listing do not return URL, it is not needed (it's a mistake of mine)

2024-06-26 12:35 UTC, XREvo commented on pkg/proxy/endpoint.go
> +		metrics.Download.With(prometheus.Labels{}).Inc()
After testing it, I see that I can't code it by simply removing the `With(prometheus.Labels{})` part :
```bash
❯ go build
# github.com/boring-registry/boring-registry/pkg/proxy
pkg/proxy/endpoint.go:31:20: metrics.Download.Inc undefined (type *prometheus.CounterVec has no field or method Inc)
```
I must at least specify it with `nil` value for labels

2024-06-26 18:58 UTC, oliviermichaelis commented on pkg/proxy/endpoint.go
> +		metrics.Download.With(prometheus.Labels{}).Inc()
You're right, let's leave it like it is. I think I recently spent too much time with other languages where the Prometheus library has a different API :)

2024-06-26 19:00 UTC, oliviermichaelis requested changes
Just one small typo left

2024-06-26 19:00 UTC, oliviermichaelis commented on pkg/core/proxifier.go
> +)49
I guess this shouldn't be here? :)

2024-06-28 14:28 UTC, XREvo commented
Everything has been fixed

2024-07-01 22:38 UTC, oliviermichaelis commented
How did you get it to work on your machine?
I tried it with S3 and `--download-proxy`, only to get 404s:
```shell
terraform init

Initializing the backend...
Initializing modules...
Downloading <redacted>:5601/hashicorp/tls-private-key/aws 0.1.1 for test...
╷
│ Error: Failed to download module
│
│   on main.tf line 1:
│    1: module "test" {
│
│ Could not download module "test" (main.tf:1) source code from
│ "https://<redacted>:5601/v1/proxy/modules%2Fhashicorp%2Ftls-private-key%2Faws%2Fhashicorp-tls-private-key-aws-0.1.1.tar.gz%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%<redacted>%252Feu-central-1%252Fs3%252Faws4_request%26X-Amz-Date%3D20240701T223153Z%26X-Amz-Expires%3D300%26X-Amz-SignedHeaders%<redacted>":
│ error downloading
│ 'https://<redacted>:5601/v1/proxy/modules%2Fhashicorp%2Ftls-private-key%2Faws%2Fhashicorp-tls-private-key-aws-0.1.1.tar.gz%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%<redacted>%252Feu-central-1%252Fs3%252Faws4_request%26X-Amz-Date%3D20240701T223153Z%26X-Amz-Expires%3D300%26X-Amz-SignedHeaders%<redacted>':
│ bad response code: 404.
╵
```

It must have something to do with the route handler not matching the `/v1/proxy/{url}` :thinking:

2024-07-02 09:52 UTC, XREvo commented
I've just re-tested everything (an e2e test with our current internal modules) and found bugs.

i've pushed the fixes:
- i've deleted the URL encoding, which was causing issues
- i've rewrote the handler's pattern and the url extractor for the proxy

Right now it works on my machine and on our test server

2024-07-10 22:38 UTC, oliviermichaelis commented
Some good news: I tested it for S3, MinIO, and GCS and it works perfectly! However, it doesn't work for Azure unfortunately.

The blob storage URLs are of the following format:
```
https://<storageAccount>.blob.core.windows.net/<storageContainer>/providers%2Fhashicorp%2Frandom%2Fterraform-provider-random_2.0.0_linux_amd64.zip?se=2024-07-11T00%3A32%3A30Z&sig=<redacted>&ske=2024-07-11T02%3A27%3A30Z&skoid=<redacted>&sks=b&skt=2024-07-10T22%3A27%3A30Z&sktid=<redacted>&skv=2023-11-03&sp=r&spr=https&sr=b&sv=2023-11-03
```

I think the `/proxy` endpoint unescapes the URL which results in the following `url` muxVar:
```
boring-registry/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip\
```

The resulting download URL looks like this:
```
https://<storageAccount>.blob.core.windows.net//<storageContainer>/providers/hashicorp/random/terraform-provider-random_2.0.0_linux_amd64.zip\?se\=2024-07-11T00%3A32%3A30Z\&sig\=<redacted>\&ske\=2024-07-11T02%3A27%3A30Z\&skoid\=<redacted>\&sks\=b\&skt\=2024-07-10T22%3A27%3A30Z\&sktid\=<redacted>\&skv\=2023-11-03\&sp\=r\&spr\=https\&sr\=b\&sv\=2023-11-03
```

2024-07-12 08:11 UTC, XREvo commented
One of my colleagues gave me an access to a Storage Account on his tenant, in order to debug the situation.

I created a directory structure to host a Terraform module:  
![image](https://github.com/user-attachments/assets/d16b419d-126a-4a74-a570-13203514a8f1)

Which allowed me to download the module via the proxy URL:  
![image](https://github.com/user-attachments/assets/e964a016-6cf4-4510-a996-0de2c9e2ae83)

The bug was in the method used to rebuild the original storage URL. Since I didn't known how client URL would be formed, I implemented an string concatenation that was invalid

It works locally for me, can you test it again?

2024-07-12 12:20 UTC, oliviermichaelis approved these changes
I just tested it, everything works now :tada: 

Thank you for your contribution, I really appreciate it!

2024-07-12 12:23 UTC, merged

2024-07-12 14:55 UTC, XREvo commented
Thank you @oliviermichaelis  
It's a pleasure to work with you

And if you need help to implement anything else, just ping me